#!/usr/bin/expect -f

set force_conservative 1  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout -1
spawn rclone config
match_max 100000
expect "e/n/d/r/c/s/q> "
send -- "d\r"
expect "remote> "
send -- "1\r"
expect "n/s/q> "
send -- "q\r"
expect eof
